Fix inaccurate "As mentioned above" assertion
bootdotdev/blog pull request #109
Opened 2024-03-14 13:05 UTC by teogeos

At some point the article says "As mentioned above, non-exported (lowercase) fields are ignored by the marshaler.". But there is no such previous mention (nor any later mention).

2024-05-12 15:34 UTC, teogeos commented
Hello @wagslane !
Anything I need to do to have this PR reviewed?

2024-06-21 14:39 UTC, skovranek approved these changes

2024-06-21 14:45 UTC, skovranek commented
@teogeos ignore the red X check, that's deprecated

2024-06-21 14:55 UTC, skovranek commented
Thank you, I'm going use this change but add a source as well.

2024-06-21 14:57 UTC, skovranek requested changes
we should include a source

2024-06-21 14:57 UTC, closed without merging