post: Is there a course on X
bootdotdev/blog pull request #111
Opened 2024-04-05 21:15 UTC by cappe987

The idea for this post came from a recent discussion in the Rust channel in the Discord server. I reused a cover image from another post, I hope that's ok. I can remove the joke about Boots if you want.

As I started making this PR I read the contributing guidelines and realized you don't want a wall of text, but I'll submit this now and if you don't like it I can try to rewrite it.

2024-06-21 15:12 UTC, skovranek commented on content/education/is-there-a-course-on.md
> +language Y, but it also doesn't need to. At this point, nothing is stopping you
tiny nit: How about a little bit more emphasis on the futility of chasing shifting trends?

The curriculum didn't teach you about currently trending framework X or language Y, but it also doesn't need to.

2024-06-21 15:14 UTC, skovranek requested changes
Nice and to the point. Left a few nit comments.

Please reformat it without line breaks.

2024-07-26 10:21 UTC, cappe987 commented
I just now saw you had removed your comments haha. I reformatted without line breaks so each paragraph is on a single line to match with the rest of the codebase. This doesn't matter according to the CommonMark spec (and most other implementations) used by Hugo. A single line break formats it the same as no line break. https://spec.commonmark.org/0.17/#paragraphs

I like to wrap my lines since that makes the Vim movement with lines correct. A line only visually wrapped in the editor looks like multiple lines but Vim treats it as one.

2024-07-26 10:25 UTC, cappe987 commented
Also updated the date of the post to today.

2024-07-26 20:54 UTC, merged