bulid blog aggregator as a tutorial
bootdotdev/blog pull request #140
Opened 2024-09-17 18:17 UTC by wcwagner22

Rough Draft, copied the information into another .md file similar to the other python tutorial we have.

2024-09-17 18:21 UTC, wagslane requested changes

2024-09-17 18:21 UTC, wagslane commented on content/tutorials/build-blog-aggregator.md
> +# Welcome
Reevaluate all these headings:

1. Each step title should be an h2 element (2 pounds)
2. Step stub headings should be h3s or h4s as appropriate (its a tree structure)

2024-09-17 18:21 UTC, wagslane commented on content/tutorials/build-blog-aggregator.md
> +  - "python"
This is a Go project

2024-09-17 18:22 UTC, wagslane commented on content/tutorials/build-blog-aggregator.md
> +  - /https://storage.googleapis.com/qvault-webapp-dynamic-assets/course_assets/EqY2AKt.png
use the image-min script and add this as a file in the project. Winston should be able to help with this

```
npm run image-min
```

2024-09-18 12:58 UTC, wcwagner22 commented
Had some issues with committing this one, I was updated on the branch but it kept telling me I was outdated. Did a force, lmk if I messed anything up

2024-09-18 14:27 UTC, wagslane approved these changes

2024-09-18 14:28 UTC, merged