Contributing the blog post: different-types-of-functions-in-programming
bootdotdev/blog pull request #23
Opened 2022-10-09 01:16 UTC by EteimZ

Article name: different-types-of-functions-in-programming.

The article talks about the different types of functions used in programming.

2022-10-10 13:43 UTC, wagslane requested changes
This is good, I think we can definitely get it to a publishable point! Some of the wording and grammar could be improved - if you haven't yet, please run it through grammarly and take a look at my other comments :)

2022-10-10 13:43 UTC, wagslane commented on content/stories/different-types-of-functions-in-programming.md
> +One exciting thing about functions is they come in different shapes and sizes figuratively at least.
Please rework the grammar here

2022-10-10 13:43 UTC, wagslane commented on content/stories/different-types-of-functions-in-programming.md
> +title: "Different types of functions in programming"
I think it would be good to narrow the focus of the article: "A Guide to all the Types of Functions in Python" might be better

2022-10-10 13:43 UTC, wagslane commented on content/stories/different-types-of-functions-in-programming.md
> +## Functions
"Plain Functions" maybe? It's weird to call the first function type just "function"

2022-10-10 13:43 UTC, wagslane commented on content/stories/different-types-of-functions-in-programming.md
> +Pure functions are just like functions but they perform no side effects. They are similar to functions in mathematics, they take in an input and produce an output. Without altering any external state
Please include a link to functions in math, maybe a wikipedia article. Not all readers will be familiar with mathematical functions

2022-10-12 01:48 UTC, EteimZ commented on content/stories/different-types-of-functions-in-programming.md
> +One exciting thing about functions is they come in different shapes and sizes figuratively at least.
Noted

2022-10-12 01:49 UTC, EteimZ commented on content/stories/different-types-of-functions-in-programming.md
> +title: "Different types of functions in programming"
Okay

2022-10-12 23:36 UTC, EteimZ commented on content/stories/different-types-of-functions-in-programming.md
> +## Functions
Changed the name to "impure functions"

2022-10-12 23:38 UTC, EteimZ commented
All changes have been made based on review.

2022-10-14 18:54 UTC, wagslane approved these changes

2022-10-14 18:54 UTC, merged